import type { Exercise } from './types'

export const starterExercises: Exercise[] = [
  {
    id: 'develop-before-adventure',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w kq - 4 5',
    sideToMove: 'white',
    title: 'Finish the setup',
    concepts: ['development', 'kingSafety', 'center'],
    prompt: 'Find a strong move. What does this position want next?',
    explanation: 'Both sides are contesting the center. Keep improving your pieces and be ready to meet the central tension.',
    suggestedMoves: ['d2d3', 'f1e1', 'c3e2'],
    opponentPlan: 'Black wants to finish development and castle, or strike with ...d5 if the center is loose.',
        nextThought: 'After Black castles, find your slowest safe improvement before opening the center.',
    openingMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1c4', 'f8c5', 'e1g1', 'g8f6'],
  },
  {
    id: 'punish-f6',
    fen: 'rnbqkbnr/pppp2pp/5p2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3',
    sideToMove: 'white',
    title: 'An invitation to improve',
    concepts: ['development', 'kingSafety', 'center'],
    prompt: 'Black just played ...f6. What should you be trying to accomplish?',
    explanation: 'Black weakened the king and spent a tempo without developing. You do not need a forced punishment: develop, control the center, and prepare to castle.',
    suggestedMoves: ['f1c4', 'd2d4', 'b1c3'],
    opponentPlan: 'Black wants to survive the opening; ...f6 weakened the king and the e5 pawn.',
        nextThought: 'Aim at e5 and the weakened diagonal. Do not rush an attack before castling.',
    openingMoves: ['e2e4', 'e7e5', 'g1f3', 'f7f6'],
  },
  {
    id: 'sicilian-find-the-break',
    fen: 'rnbqkb1r/pp2pppp/3p1n2/8/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 1 5',
    sideToMove: 'white',
    title: 'Asymmetry is the point',
    concepts: ['center', 'development', 'activity'],
    prompt: 'The position is asymmetric. What should you improve before the next central clash?',
    explanation: 'The Sicilian gives both sides different plans. Develop with purpose, keep pressure on the center, and remember that the d4 square is a strategic target.',
    suggestedMoves: ['b1c3', 'c1e3', 'c1g5'],
    opponentPlan: 'Black is preparing ...e5 or ...Nc6 to finish development and fight for d4.',
        nextThought: 'Decide whether to meet ...e5 with a push, an exchange, or extra central support.',
    openingMoves: ['e2e4', 'c7c5', 'g1f3', 'd7d6', 'd2d4', 'c5d4', 'f3d4', 'g8f6'],
  },
  {
    id: 'french-chain-base',
    fen: 'rnbqkbnr/pp3ppp/4p3/2ppP3/3P4/8/PPP2PPP/RNBQKBNR w KQkq - 0 4',
    sideToMove: 'white',
    title: 'Read the pawn chain',
    concepts: ['center', 'activity', 'development'],
    prompt: 'The center is closed for now. Where should your pressure and development point?',
    explanation: 'Closed centers make pawn structure important. Develop around the chain, identify its base, and prepare the break that changes the position.',
    suggestedMoves: ['g1f3', 'c2c3', 'c1e3'],
    opponentPlan: 'Black wants ...c5 pressure and then ...Nc6, hitting the base of your chain.',
        nextThought: 'Support e5 and prepare c3 before Black’s counterplay arrives.',
    openingMoves: ['e2e4', 'e7e6', 'd2d4', 'd7d5', 'e4e5', 'c7c5'],
  },
  {
    id: 'caro-kann-bishop',
    fen: 'rn1qkbnr/pp2pppp/2p5/3pPb2/3P4/8/PPP2PPP/RNBQKBNR w KQkq - 1 4',
    sideToMove: 'white',
    title: 'The solid center',
    concepts: ['development', 'center', 'kingSafety'],
    prompt: 'Black has built a solid center. What useful piece improvement comes first?',
    explanation: 'The Caro-Kann is solid because Black intends to free the light-squared bishop. Use development and central pressure to make that plan costly or slow.',
    suggestedMoves: ['g1f3', 'f1d3', 'c2c4'],
    opponentPlan: 'Black wants ...e6 and ...Bf5 freed, then ...c5 to challenge d4.',
        nextThought: 'Develop the knight before committing pawns, and keep the c4 idea in reserve.',
    openingMoves: ['e2e4', 'c7c6', 'd2d4', 'd7d5', 'e4e5', 'c8f5'],
  },
  {
    id: 'queens-pawn-tension',
    fen: 'rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 2 4',
    sideToMove: 'white',
    title: 'Keep the tension useful',
    concepts: ['center', 'development', 'kingSafety'],
    prompt: 'The center is contested but not resolved. What improves your position without rushing?',
    explanation: 'Queen’s Pawn positions reward patient development. Keep central tension when it helps your pieces and prepare the next useful break.',
    suggestedMoves: ['c4c5', 'c1g5', 'g1f3'],
    opponentPlan: 'Black will keep the tension with ...c6 or ...Be7, waiting to see your plan.',
        nextThought: 'If the tension resolves, decide early whether the open file or the extra tempo helps you more.',
    openingMoves: ['d2d4', 'd7d5', 'c2c4', 'e7e6', 'b1c3', 'g8f6'],
  },
  {
    id: 'hypermodern-center',
    fen: 'rnbqk2r/ppppppbp/5np1/8/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 2 4',
    sideToMove: 'white',
    title: 'A big center needs support',
    concepts: ['center', 'development', 'kingSafety'],
    prompt: 'Black is letting you occupy space. How do you make that space useful?',
    explanation: 'A large center is an asset only when it is supported and developed behind. Do not expand automatically; build a position that can hold the space.',
    suggestedMoves: ['e2e4', 'g1f3', 'c1f4'],
    opponentPlan: 'Black wants ...d5 or pressure on d4 from the g7 bishop.',
        nextThought: 'Ask whether ...d5 would give you a useful tempo or free Black’s game.',
    openingMoves: ['d2d4', 'g8f6', 'c2c4', 'g7g6', 'b1c3', 'f8g7'],
  },
  {
    id: 'spanish-development',
    fen: 'r1bqkbnr/1ppp1ppp/p1n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    sideToMove: 'white',
    title: 'Pressure without hurry',
    concepts: ['development', 'kingSafety', 'center'],
    prompt: 'Your bishop has created pressure. What is the position’s next practical priority?',
    explanation: 'Pressure on the knight is useful, but development and king safety still matter more than forcing an immediate answer.',
    suggestedMoves: ['e1g1', 'f1c4', 'b1c3'],
    opponentPlan: 'Black will support e5 with ...d6 and develop toward castling.',
        nextThought: 'Castle first, then decide whether d3 solid development or an early d4 break suits you.',
    openingMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1b5', 'a7a6'],
  },
]
